### ISSUE TITLE
DoubleRelease issue

### ISSUE THREAD

**Issue by aayushnarang** [ofkindness/winston-postgres-transport#13]
Getting an error every time using logger.

My Config

```
const logger = winston.createLogger({

  format: format.combine(
    format.colorize(),
    format.timestamp({
      format: 'YYYY-MM-DD HH:mm:ss',
    }),
    format.printf(info => `${info.timestamp} ${info.level}: ${info.message}`),
  ),

  transports: [
    new winston.transports.Console(options.console),
    new winston.transports.File(options.file),
    new Postgres({
      connectionString: `postgres://${userName}:${password}@${hostName}:${dbPort}/${dbName}`,
      level: 'info',
      poolConfig: {
        connectionTimeoutMillis: 0,
        idleTimeoutMillis: 0,
        max: 10,
      },
      tableName: 'winston_logs',
    }),
  ],
});
```

```
(node:71328) UnhandledPromiseRejectionWarning: Error: Release called on client which has already been released to the pool.
    at throwOnDoubleRelease (/Users/lalitjoshi/Workspace/React/live-objects/node_modules/winston-pg-native/node_modules/pg-pool/index.js:29:9)
    at module.exports.client.release (/Users/lalitjoshi/Workspace/React/live-objects/node_modules/winston-pg-native/node_modules/pg-pool/index.js:251:9)
    at /Users/lalitjoshi/Workspace/React/live-objects/node_modules/winston-pg-native/lib/winston-pg-native.js:149:16
(node:71328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:71328) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by rajdeepratan** [comment]
I'm also facing the same issue in my project node server.

**Comment by kateile** [comment]
Did you guys find solution for this?

**Comment by rajdeepratan** [comment]
Not yet.
